// Auto-generated by pivota init-dev-server. Extends user's vite.config.ts at runtime
// to set server.allowedHosts = true (sandbox preview embedding) and host=true (so
// the dev server binds 0.0.0.0). Remove this file if you set allowedHosts yourself.
import { defineConfig, mergeConfig } from 'vite';
import userConfig from './vite.config';
export default defineConfig((env) => mergeConfig(
  typeof userConfig === 'function' ? userConfig(env) : userConfig,
  { server: { host: true, allowedHosts: true, strictPort: true } }
));
